### ISSUE TITLE
Create project and stuff

### ISSUE THREAD

**Issue by dmutroh** [PE-Pmi-32-2020/Memento#14]
1. Створити Console App (.NET Core)  проект,
Використовуючи ADO.Net підключити до
проекту вашу базу даних. На консоль вивести
дані з табличок. Створити метод в цій
консольній апп, для заповнення бази даних
тестовими рендомними даними через
ADO.Net по 30-50 записів в кожній табличці

**Comment by Andertius** [comment]
Oh yeah!
