### ISSUE TITLE
Create Dashboard

### ISSUE THREAD

**Issue by dmutroh** [PE-Pmi-32-2020/Memento#2]
Створити на гітхабі до свого проекту дошку з
стовпчиками - Planned, InProgress,
ReadyForReview, Done. На дошку додаєте всі
вказані тут завдання з описом та студентом,
який це завдання буде виконувати і трекати
по дошці до стану ReadyForReview. Рев’ю
повинен провести інший студент з команди,
написати відповідний коментар і перевести в
Done. До вказаної дати всі поставлені
завдання мають бути в Done

**Comment by Andertius** [comment]
Good job, mate
